### ISSUE TITLE
is there any example with docker? including all parameters

### ISSUE THREAD

**Issue by AlexanderKozhevin** [livekit-examples/kitt#1]

**Comment by theomonnom** [comment]
lkgpt-service is already using Docker but the meet app is a simple nextjs app

**Comment by AlexanderKozhevin** [comment]
@theomonnom yes, but what parameters to pass. is there an example?

**Comment by theomonnom** [comment]
Hey, you just need to export environment variables: 
  - LIVEGPT_CONFIG_BODY
  - OPENAI_API_KEY
  - GOOGLE_APPLICATION_CREDENTIALS_BODY
