### ISSUE TITLE
Whisper for STT

### ISSUE THREAD

**Issue by Akshay-akkay** [livekit-examples/kitt#6]
I was trying to use OpenAI's whisper for the STT service in KITT because it's open source and it's much better at transcription than Google STT.
But got stuck. Help would be appreciated.

I am using Go Bindings of Whisper.CPP (github.com/ggerganov/whisper.cpp/bindings/go)
 - `process` method of whisper requires `[]float32` of 30 secs atleast.
 - But the oggwriter has `[]byte`
 
 So I am stuck at this.

**Comment by anupriya17** [comment]
Have you made any progress we want to build similar?

Hope these links helps you:
https://github.com/go-audio/audio/blob/master/float_buffer.go#L23
https://github.com/hraban/opus/blob/v2/decoder.go#L97
https://github.com/quantum1423/tavla/blob/master/opus/decoder.go#L34

**Comment by theomonnom** [comment]
Hi, sorry this is not something planned to do on Kitt, I think you could easily do this with our Python SDK
